name: TntGun
version: 3.3
main: fr.themsou.main.main
description: Plugin principal de TntGun
author: themsou
api-version: 1.13
commands:
  ?:
  help:
  spawn:
  hub:
  lobby:
  l:
  login:
  reg:
  register:
  claim:
  g:
  money:
  ent:
  discord:
  a:
  pay:
  rtp:
  pack:
  world:
    permission: tntgun.world
  setmoney:
    permission: tntgun.setmoney
  grade:
    permission: tntgun.grade
  config:
    permission: tntgun.config
  misc:
    permission: tntgun.mics